event:
    path:     /
    defaults: { _controller: "YodaEventBundle:Event:index" }

event_show:
    path:     /{slug}/show
    defaults: { _controller: "YodaEventBundle:Event:show" }

event_new:
    path:     /new
    defaults: { _controller: "YodaEventBundle:Event:new" }

event_create:
    path:     /create
    defaults: { _controller: "YodaEventBundle:Event:create" }
    methods:  POST

event_edit:
    path:     /{slug}/edit
    defaults: { _controller: "YodaEventBundle:Event:edit" }

event_update:
    path:     /{slug}/update
    defaults: { _controller: "YodaEventBundle:Event:update" }
    methods:  [POST, PUT]

event_delete:
    path:     /{slug}/delete
    defaults: { _controller: "YodaEventBundle:Event:delete" }
    methods:  [POST, DELETE]

event_attend:
    path:     /{slug}/attend.{format}
    defaults: { _controller: "YodaEventBundle:Event:attend", format: html }
    requirements:
      format: json

event_unattend:
    path:     /{slug}/unattend.{format}
    defaults: { _controller: "YodaEventBundle:Event:unattend", format: html }
    requirements:
      format: json
