yoda_event_event:
    resource: "@YodaEventBundle/Resources/config/routing/event.yml"
    prefix:   /

yoda_event_homepage:
    path:     /hello/{name}/{count}
    defaults: { _controller: YodaEventBundle:Default:index }
