yoda_event:
    resource: "@YodaEventBundle/Resources/config/routing.yml"
    prefix:   /

user_controller:
    resource: "@UserBundle/Controller"
    prefix:   /
    type:     annotation

yoda_controller:
    resource: "@YodaEventBundle/Controller"
    prefix:   /
    type:     annotation